#define KEY_BATTERY_LEVEL_MIN 1
#define KEY_BATTERY_LEVEL_MAX 100
#define KEY_BATTERY_CHARGING_NONE 101
#define KEY_BATTERY_CHARGING_USB 102
#define KEY_BATTERY_CHARGING_SET 103
#define KEY_BATTERY_LEVEL 110
#define KEY_BATTERY_CHARGING 111

#define KEY_NETWORK_WIFI 201
#define KEY_NETWORK_MOBILE 202
#define KEY_NETWORK_WIFI_MOBILE 203
#define KEY_NETWORK_OFF 204
#define KEY_NETWORK 210
  
#define KEY_WEATHER 300

#define KEY_DATE 400

static int const PEBBLE_SCREEN_WIDTH = 144;
static int const PEBBLE_SCREEN_HEIGHT = 168;