#define KEY_BATTERY_LEVEL_MIN 1
#define KEY_BATTERY_LEVEL_MAX 100
#define KEY_BATTERY_CHARGING_NONE 101
#define KEY_BATTERY_CHARGING_USB 102
#define KEY_BATTERY_CHARGING_SET 103
#define KEY_BATTERY_CHARGING_WIRELESS 104
#define KEY_BATTERY_LEVEL 110
#define KEY_BATTERY_CHARGING 111

#define KEY_NETWORK_WIFI 201
#define KEY_NETWORK_MOBILE 202
//#define KEY_NETWORK_WIFI_MOBILE 203
#define KEY_NETWORK_OFF 204
#define KEY_NETWORK 210
  
#define KEY_WEATHER 300

static int const PEBBLE_SCREEN_WIDTH = 144;
static int const PEBBLE_SCREEN_HEIGHT = 168;

static int const TRANSPARENT_BATTERY_X = 94;
static int const TRANSPARENT_BATTERY_Y = 127;
static int const TRANSPARENT_BATTERY_W = 36;
static int const TRANSPARENT_BATTERY_H = 30;